CREATE TABLE public.USERS (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(40) NOT NULL,
    mail VARCHAR(40) NOT NULL,
    password VARCHAR(255) NOT NULL,
    nickname VARCHAR(40),
    dateOfBirth date not null
);